### ISSUE TITLE
Not able to link media files to Media objects

### ISSUE THREAD

**Issue by Sholofly** [Krevo/WherigoTools#2]
Hi,
I love your script. 
Is it possible for you to rename the extracted media files having their id (Guid) in the file name?
For now it's not possibe to link the extracted media files to the objects in the generated lua file.

**Comment by Krevo** [comment]
Hi,
Thanks for your interest.

In the lua source code, for each media I can see some lines like this =>

```
_TGu = Wherigo.ZMedia(_V2tgY)
_TGu.Id = "c74e000a-bb02-4088-8788-96263f8d8c47"
-- happyhalloween
_TGu.Name = _oII("u\fbbeu\f==\027Q\v\vC")
_TGu.Description = ""
_TGu.AltText = ""
_TGu.Resources = {
  {
    Type = "mp3",
    Filename = "happyhalloween.mp3",
    Directives = {}
  }
}
```

I think, that I can rename the media file with the original filename (in this example it will be "happyhalloween.mp3" instead of "cartridge_name_n.ext")

**Comment by Sholofly** [comment]
Thanks for the reply. That would be nice!

**Comment by Sholofly** [comment]
Is there a way to help you develop? I'm a developer so maybe there is a way to assist?

**Comment by Krevo** [comment]
Don't worry. I've done something yesterday. Will commit soon.

**Comment by Krevo** [comment]
Please try with the last commit.

**Comment by Sholofly** [comment]
Simply brilliant! Thank you for acting so quickly!
