### ISSUE TITLE
How to use finduanswer.php

### ISSUE THREAD

**Issue by Githubertnik** [Krevo/WherigoTools#3]
I need some help on how to use finduanswer.php
I have hashe _FI9uc.Id = "2ff1bd37-bc39-464a-b9a6-d9d2425974df"
The result should be a number but ... can't get the answer.

**Comment by RGBYCP** [comment]
I would like to join. I have a hash with value equal to 32536.
Output:
```
php finduanswer.php 32536          
First collision found =>

All collisions found for length 4 =>

```
I don't see any useful output. I don't know how to fix this. Thank you.

**Comment by Krevo** [comment]
> I would like to join. I have a hash with value equal to 32536. Output:
> 
> ```
> php finduanswer.php 32536          
> First collision found =>
> 
> All collisions found for length 4 =>
> ```
> 
> I don't see any useful output. I don't know how to fix this. Thank you.

No collision where found with the default length of 4 letters.

You cans try 5 letters by typing :
`php finduanswer.php 32536 5`

The output will be : 
```
First collision found =>
arbuk
All collisions found for length 5 =>
arbuk
arcmv
asnsw
atyyx
...
```

I guess, I can modify the script so when nothing is found with 4 letters, 5 letters is tried next.

**Comment by Krevo** [comment]
> I need some help on how to use finduanswer.php I have hashe _FI9uc.Id = "2ff1bd37-bc39-464a-b9a6-d9d2425974df" The result should be a number but ... can't get the answer.

I think you are not correctly identifying the hash you want to decrypt, LOOK FOR A LINE LIKE (where hash_to_find is a number between 0 and 65535) : 
`if _Urwigo.Hash(string.lower(input)) == hash_to_find`

I may look for you, if you tell me what Wherigo cartridge is it ?

**Comment by RGBYCP** [comment]
@Krevo Thank you very much. I did not know I have to put `5` after it. But it worked now. Sorry, but thank you for your help.
Suggestion: Maybe if the user forgets to put in the length of the numbers, one could add it by default and continue to the next one when nothing was found?

**Comment by Githubertnik** [comment]
Thanks for reply. Now I know what exactly to search.

I have also found out that some answers are not coded but you must search the program code. 
Here is the example were you have to search for "_abcSA" to find the "function _abcSA:OnGetInput(input)".

_abcSA = Wherigo.ZInput(_5N1Bp)
_abcSA.Id = "bde34723-acd6-7293-98fe-3215698a79e9"
-- FindTheYearOfBirth
_abcSA.Name = _HXqh("xxxxyyyyxxxxyyyy")
_abcSA.Description = ""
_abcSA.Visible = true
_abcSA.InputType = "Text"
_abcSA.Text = _HXqh("Description what to search")

....
....
....

function _abcSA:OnGetInput(input)
  input = tonumber(input)
  if input == nil then
    return
  end
  if input == 1922 then
    _Urwigo.MessageBox({
-- Correct answer
      Text = _HXqh("Hfz={ovs\348"),
      Buttons = {
-- Wrong answer
        _HXqh("NB\019CUd3d/r/iwW{p+x=Zvfopl\228")
      },
      Callback = function(action)
        if action ~= nil then
          _OM9zd.Active = false
          _0gB()
        end
      end
    })
  else
    _XAwoa()
  end

**Comment by Krevo** [comment]
If you see a line like `if input == 1922 then` , then there is no use of the Hash function and you have your answer directly (`1922`).

**Comment by Krevo** [comment]
> @Krevo Thank you very much. I did not know I have to put `5` after it. But it worked now. Sorry, but thank you for your help. Suggestion: Maybe if the user forgets to put in the length of the numbers, one could add it by default and continue to the next one when nothing was found?

Done in the Christmas release commited yesterday.
