### ISSUE TITLE
Uncaught TypeError suddenly

### ISSUE THREAD

**Issue by PythonSchlumpf** [Krevo/WherigoTools#4]
Hi Krevo,
I get suddenly 
```
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /Users/Downloads/WhereIgo/Test/WherigoTools-master/wherigoreader.php:261
Stack trace:
#0 /Users/Downloads/WhereIgo/Test/WherigoTools-master/wherigoreader.php(261): implode(Array, ', ')
#1 {main}
```
I don't know how to fix this. Could you help me please?

**Comment by PythonSchlumpf** [comment]
Solved it, swope the order in implode.

**Comment by Krevo** [comment]
Sorry, for my absence of answer. I will commit a modified version !!
The implode() function was historically accepting two different order of parameters in old php versions.

**Comment by PythonSchlumpf** [comment]
Dear Francois,

No worries. Yes, that is right. I googled the error, found it and fixed
your script here, now it works again. You don't know how much I love your
script. Many thanks.
Best regards
P-Schlumpf
